import "app/[lang]/globals.css";
import type { Metadata } from "next";
import { Providers } from "app/[lang]/providers";
import classNames from "classnames";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang} suppressHydrationWarning>
      <head />
      <body className={classNames("bg-white", "dark:bg-dark")}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
